### ISSUE TITLE
python setup

### ISSUE THREAD

**Issue by telephon** [capital-G/musikinformatik-sose2021#7]
At least in the context of this course, it would be useful to provide a link how to get python3 (e.g. homebrew), and also how to upgrade pip3 if there is not the right version.

**Comment by capital-G** [comment]
At the top of https://capital-g.github.io/musikinformatik-sose2021/docs/course-info/setup.html#environment-setup

<img width="588" alt="image" src="https://user-images.githubusercontent.com/8267062/114271621-95e78900-9a12-11eb-9db4-09b0c3b1bb30.png">

there is a link to https://realpython.com/installing-python/ which should cover this - did you use this link?

**Comment by capital-G** [comment]
## ToDo

* [ ] Lets move the link for python install down
* [ ] declare that only major versions are important
* [ ] explain folder `venv` and the repository folder structure

**Comment by capital-G** [comment]
@telephon check https://github.com/capital-G/musikinformatik-sose2021/pull/14/files for improved setup - not yet included in the site and please no merge yet
